# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60869713b6862553a85f7b6e9e94df3bc7241bdd26453009ba7af189e2d66dfc8be81c9c2bc65b2fc223be7cb390f0b556a669f104c6dc6b36cc6b338e078429

test:
  secret_key_base: 7d291e58fdacbf1c8956bf7b8c0f42841add17bd89094481484f6cd591f6917095e4195bb7f2e970db66be6858e4fa5dee6ad631fade96fd81fd8c3f18ebcffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
